myfirst/apps/articles/urls.py
from django.urls import path

from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('<int:article_id>/leave_comment/',
         views.leave_comment, name='leave_comment')
]

# /articles/
# /articles/1

myfirst/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^articles/', include('articles.urls')),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
]

articles/models.py
from django.db import models

# Create your models here.

myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('article title', max_length = 200)
    article_text = models.TextField('article text')
    pub_date = models.DateTimeField('publication date')

    def __str__(self):
        return self.article_title

    def recently_published(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('author name', max_length = 50)
    comment_text = models.CharField('comment text', max_length = 200)


def __str__(self):
        return self.author_name

articles/views.py
from django.shortcuts import render

# Create your views here.

myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article, Comment

def index(request):
    latest_articles_list = Article.objects.order_by('pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
       raise Http404('Article not found')

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
       raise Http404('Article not found')

    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

    return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

myfirst/templates/articles/detail.html
{% extends 'base.html' %} 

{% block title %}

        {{ article.article_title }}
        
{% endblock %} 

{% block content %} 

    <h2>{{ article.article_title }}</h2>

    <p>{{ article.article_text }}</p>

    <em>{{ article.pub_date }}</em>

    <hr>
    
    {% if latest_comments_list %}

        {% for c in latest_comments_list %}
                <strong>{{c.author_name}}</strong>
                <p>{{c.comment_text}}</p>
        {% endfor %}

    {% else %}
        Comments are not found! Be the first to add a comment :-)
    {% endif %}
    
    <hr>

    <form action="{% url 'articles:leave_comment' article.id %}" method="post">
    
        {% csrf_token %}
        <input type="text" required placeholder="Your name" name="name"><br>
        <textarea name="text" required placeholder="Enter comment here" cols="80" rows="10"></textarea><br>

        <button type="submit">Leave a Comment</button>
    
    </form>

{% endblock %}

myfirst/templates/articles/list.html
{% extends 'base.html' %} 

{% block title %}Last Articles{% endblock %} 

{% block content %} 

        {% if latest_articles_list %} <br />

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{ a.article_title }}</a
            > <br />
        {% endfor %} 
        {% else %} 
            Articles not found 
        {% endif %} 
{% endblock %}

myfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>{% block title %}Django Blog{% endblock %}</title>
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>